"""delete column agreed_customer agreed_executor into executor_order_cancellations customer_order_cancellations

Revision ID: 086524442db5
Revises: 240afa72afd8
Create Date: 2026-03-26 14:01:47.513263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086524442db5'
down_revision: Union[str, Sequence[str], None] = '240afa72afd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order_cancellations', 'agreed_executor')
    op.drop_column('executor_order_cancellations', 'agreed_customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('agreed_customer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('agreed_executor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
