"""delete columns from notifications

Revision ID: 0b19a865b1b2
Revises: abec7211f133
Create Date: 2026-08-31 18:09:16.999526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b19a865b1b2'
down_revision: Union[str, Sequence[str], None] = 'abec7211f133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'executor_reaction')
    op.drop_column('notifications', 'acknowledged_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('executor_reaction', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
