"""delete column currency from executor_order_cancellations customer_order_cancellations

Revision ID: 1897f4855b07
Revises: 68079abe22f9
Create Date: 2026-04-10 19:43:13.534645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1897f4855b07'
down_revision: Union[str, Sequence[str], None] = '68079abe22f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order_cancellations', 'currency')
    op.drop_column('executor_order_cancellations', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
