"""add columns unto tables customer_order_cancellations executor_order_cancellations

Revision ID: 1ad474910711
Revises: 645f041ba428
Create Date: 2026-04-06 17:45:52.298861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad474910711'
down_revision: Union[str, Sequence[str], None] = '645f041ba428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_cancellations', sa.Column('refund_strategy', sa.String(length=20), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_amount_customer', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_amount_executor', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_reason_text', sa.Text(), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_status', sa.String(length=20), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_strategy', sa.String(length=20), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_amount_customer', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_amount_executor', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_reason_text', sa.Text(), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor_order_cancellations', 'refund_status')
    op.drop_column('executor_order_cancellations', 'refund_reason_text')
    op.drop_column('executor_order_cancellations', 'currency')
    op.drop_column('executor_order_cancellations', 'refund_amount_executor')
    op.drop_column('executor_order_cancellations', 'refund_amount_customer')
    op.drop_column('executor_order_cancellations', 'refund_strategy')
    op.drop_column('customer_order_cancellations', 'refund_status')
    op.drop_column('customer_order_cancellations', 'refund_reason_text')
    op.drop_column('customer_order_cancellations', 'currency')
    op.drop_column('customer_order_cancellations', 'refund_amount_executor')
    op.drop_column('customer_order_cancellations', 'refund_amount_customer')
    op.drop_column('customer_order_cancellations', 'refund_strategy')
    # ### end Alembic commands ###
