"""change column topik on topic in table support_conversations

Revision ID: 217e364436d8
Revises: bf4eb5232097
Create Date: 2026-04-15 17:39:43.718203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217e364436d8'
down_revision: Union[str, Sequence[str], None] = 'bf4eb5232097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_conversations', sa.Column('topic', sa.String(length=50), nullable=True))
    op.drop_column('support_conversations', 'topik')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_conversations', sa.Column('topik', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('support_conversations', 'topic')
    # ### end Alembic commands ###
