"""change column agreed_customer customer_comment into executor_order_cacellations

Revision ID: 240afa72afd8
Revises: 4cc68c0dbd6d
Create Date: 2026-03-25 18:27:01.940007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240afa72afd8'
down_revision: Union[str, Sequence[str], None] = '4cc68c0dbd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('agreed_customer', sa.Boolean(), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('customer_comment', sa.Text(), nullable=True))
    op.drop_column('executor_order_cancellations', 'executor_comment')
    op.drop_column('executor_order_cancellations', 'agreed_executor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('agreed_executor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('executor_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('executor_order_cancellations', 'customer_comment')
    op.drop_column('executor_order_cancellations', 'agreed_customer')
    # ### end Alembic commands ###
