"""add column into customer_id into customer_order_cancellations executor_id into executor_order_cancellations

Revision ID: 3a549675b45d
Revises: e34cc5b97f1b
Create Date: 2026-03-22 20:53:01.989049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a549675b45d'
down_revision: Union[str, Sequence[str], None] = 'e34cc5b97f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_cancellations', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('customer_order_cancellations_admin_id_fkey'), 'customer_order_cancellations', type_='foreignkey')
    op.create_foreign_key(None, 'customer_order_cancellations', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customer_order_cancellations', 'admin_comment')
    op.drop_column('customer_order_cancellations', 'status')
    op.drop_column('customer_order_cancellations', 'admin_id')
    op.add_column('executor_order_cancellations', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('executor_order_cancellations_admin_id_fkey'), 'executor_order_cancellations', type_='foreignkey')
    op.create_foreign_key(None, 'executor_order_cancellations', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('executor_order_cancellations', 'admin_comment')
    op.drop_column('executor_order_cancellations', 'status')
    op.drop_column('executor_order_cancellations', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'executor_order_cancellations', type_='foreignkey')
    op.create_foreign_key(op.f('executor_order_cancellations_admin_id_fkey'), 'executor_order_cancellations', 'users', ['admin_id'], ['id'])
    op.drop_column('executor_order_cancellations', 'customer_id')
    op.add_column('customer_order_cancellations', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer_order_cancellations', type_='foreignkey')
    op.create_foreign_key(op.f('customer_order_cancellations_admin_id_fkey'), 'customer_order_cancellations', 'users', ['admin_id'], ['id'])
    op.drop_column('customer_order_cancellations', 'executor_id')
    # ### end Alembic commands ###
