"""delete columns  from customer_order_cancellations executor_order_cancellations

Revision ID: 499d744e79c8
Revises: 4638d6fe4c03
Create Date: 2026-04-10 18:52:26.837172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499d744e79c8'
down_revision: Union[str, Sequence[str], None] = '4638d6fe4c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order_cancellations', 'admin_comment')
    op.drop_column('customer_order_cancellations', 'refund_reason_text')
    op.drop_column('customer_order_cancellations', 'refund_status')
    op.drop_column('customer_order_cancellations', 'updated_at')
    op.drop_column('executor_order_cancellations', 'admin_comment')
    op.drop_column('executor_order_cancellations', 'refund_reason_text')
    op.drop_column('executor_order_cancellations', 'refund_status')
    op.drop_column('executor_order_cancellations', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('refund_reason_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_reason_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
