"""add column status agreed_executor executor_comment decision_admin admin_comment resolved_at into customer_order_cancellstions and executor_order_cancellations 

Revision ID: 4cc68c0dbd6d
Revises: 3a549675b45d
Create Date: 2026-03-22 21:15:46.881028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc68c0dbd6d'
down_revision: Union[str, Sequence[str], None] = '3a549675b45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_cancellations', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('agreed_executor', sa.Boolean(), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('executor_comment', sa.Text(), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('decision_admin', sa.String(length=20), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('admin_comment', sa.Text(), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('customer_order_cancellations_executor_id_fkey'), 'customer_order_cancellations', type_='foreignkey')
    op.create_foreign_key(None, 'customer_order_cancellations', 'users', ['executor_id'], ['id'], ondelete='SET NULL')
    op.add_column('executor_order_cancellations', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('agreed_executor', sa.Boolean(), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('executor_comment', sa.Text(), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('decision_admin', sa.String(length=20), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('admin_comment', sa.Text(), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor_order_cancellations', 'resolved_at')
    op.drop_column('executor_order_cancellations', 'updated_at')
    op.drop_column('executor_order_cancellations', 'admin_comment')
    op.drop_column('executor_order_cancellations', 'decision_admin')
    op.drop_column('executor_order_cancellations', 'executor_comment')
    op.drop_column('executor_order_cancellations', 'agreed_executor')
    op.drop_column('executor_order_cancellations', 'status')
    op.drop_constraint(None, 'customer_order_cancellations', type_='foreignkey')
    op.create_foreign_key(op.f('customer_order_cancellations_executor_id_fkey'), 'customer_order_cancellations', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customer_order_cancellations', 'resolved_at')
    op.drop_column('customer_order_cancellations', 'updated_at')
    op.drop_column('customer_order_cancellations', 'admin_comment')
    op.drop_column('customer_order_cancellations', 'decision_admin')
    op.drop_column('customer_order_cancellations', 'executor_comment')
    op.drop_column('customer_order_cancellations', 'agreed_executor')
    op.drop_column('customer_order_cancellations', 'status')
    # ### end Alembic commands ###
