"""add column cost currency into tables works works_masters_from_admin works_masters_myself 

Revision ID: 561553a867bf
Revises: b7c8d9e0f1a2
Create Date: 2026-06-06 22:45:45.397627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561553a867bf'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('currency', sa.String(length=100), nullable=True))
    op.add_column('works_masters_from_admin', sa.Column('cost', sa.Numeric(), nullable=True))
    op.add_column('works_masters_from_admin', sa.Column('currency', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('works_masters_from_admin_category_work_id_fkey'), 'works_masters_from_admin', type_='foreignkey')
    op.drop_column('works_masters_from_admin', 'category_work_id')
    op.add_column('works_masters_myself', sa.Column('currency', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works_masters_myself', 'currency')
    op.add_column('works_masters_from_admin', sa.Column('category_work_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('works_masters_from_admin_category_work_id_fkey'), 'works_masters_from_admin', 'categories_works', ['category_work_id'], ['id'])
    op.drop_column('works_masters_from_admin', 'currency')
    op.drop_column('works_masters_from_admin', 'cost')
    op.drop_column('works', 'currency')
    # ### end Alembic commands ###
