"""add column avatar_url into table users_profiles

Revision ID: 643dd4fd048b
Revises: 1f8a66ca60f9
Create Date: 2026-02-28 20:57:09.189809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643dd4fd048b'
down_revision: Union[str, Sequence[str], None] = '1f8a66ca60f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_url')
    # ### end Alembic commands ###
