"""add table moderation_actions add column blocked_until warning_count into table users

Revision ID: 645f041ba428
Revises: cbfba6851e58
Create Date: 2026-04-05 15:11:13.024558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645f041ba428'
down_revision: Union[str, Sequence[str], None] = 'cbfba6851e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints_conversations', 'verdict')
    op.drop_column('complaints_conversations', 'status')
    op.add_column('users', sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('warnings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'warnings_count')
    op.drop_column('users', 'blocked_until')
    op.add_column('complaints_conversations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('complaints_conversations', sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
