"""add columns admin_cooment into customer_order_cancellations executor_order_cancellations

Revision ID: 68079abe22f9
Revises: 499d744e79c8
Create Date: 2026-04-10 19:36:39.868567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68079abe22f9'
down_revision: Union[str, Sequence[str], None] = '499d744e79c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_cancellations', sa.Column('admin_comment', sa.Text(), nullable=True))
    op.add_column('executor_order_cancellations', sa.Column('admin_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor_order_cancellations', 'admin_comment')
    op.drop_column('customer_order_cancellations', 'admin_comment')
    # ### end Alembic commands ###
