"""add into tables works_estimates materials_estimates graphic_works ondelete cascade

Revision ID: 884966b9b966
Revises: bb431ccb9af3
Create Date: 2026-05-23 22:06:43.947090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884966b9b966'
down_revision: Union[str, Sequence[str], None] = 'bb431ccb9af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graphic_works', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('graphic_works', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('graphic_works_order_id_fkey'), 'graphic_works', type_='foreignkey')
    op.drop_constraint(op.f('graphic_works_user_id_fkey'), 'graphic_works', type_='foreignkey')
    op.create_foreign_key(None, 'graphic_works', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'graphic_works', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('materials_estimates_work_estimate_id_fkey'), 'materials_estimates', type_='foreignkey')
    op.create_foreign_key(None, 'materials_estimates', 'works_estimates', ['work_estimate_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('works_estimates_order_id_fkey'), 'works_estimates', type_='foreignkey')
    op.drop_constraint(op.f('works_estimates_user_id_fkey'), 'works_estimates', type_='foreignkey')
    op.create_foreign_key(None, 'works_estimates', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'works_estimates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works_estimates', type_='foreignkey')
    op.drop_constraint(None, 'works_estimates', type_='foreignkey')
    op.create_foreign_key(op.f('works_estimates_user_id_fkey'), 'works_estimates', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('works_estimates_order_id_fkey'), 'works_estimates', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'materials_estimates', type_='foreignkey')
    op.create_foreign_key(op.f('materials_estimates_work_estimate_id_fkey'), 'materials_estimates', 'works_estimates', ['work_estimate_id'], ['id'])
    op.drop_constraint(None, 'graphic_works', type_='foreignkey')
    op.drop_constraint(None, 'graphic_works', type_='foreignkey')
    op.create_foreign_key(op.f('graphic_works_user_id_fkey'), 'graphic_works', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('graphic_works_order_id_fkey'), 'graphic_works', 'orders', ['order_id'], ['id'])
    op.alter_column('graphic_works', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('graphic_works', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
