"""add column topik into table supports_conversations

Revision ID: 97b25a6eca30
Revises: d0d85a706739
Create Date: 2026-04-14 21:46:55.487156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97b25a6eca30'
down_revision: Union[str, Sequence[str], None] = 'd0d85a706739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supports_messages')
    op.drop_table('supports_conversations')
    op.add_column('support_conversations', sa.Column('topik', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_conversations', 'topik')
    op.create_table('supports_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('supports_conversations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supports_conversations_pkey'))
    )
    op.create_table('supports_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['complaint_conversation_id'], ['complaints_conversations.id'], name=op.f('supports_messages_complaint_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('supports_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supports_messages_pkey'))
    )
    # ### end Alembic commands ###
