"""change table users add column town_id

Revision ID: 9f0659bf4a65
Revises: c2d3e4f5a6b7
Create Date: 2026-08-02 17:25:05.663673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0659bf4a65'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'name_country',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('regions', 'name_region',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('towns', 'name_town',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('town_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'towns', ['town_id'], ['id'])
    op.drop_column('users', 'region')
    op.drop_column('users', 'town')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('town', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'town_id')
    op.alter_column('towns', 'name_town',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('regions', 'name_region',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('countries', 'name_country',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
