"""delete column refund_strategy from customer_order_cancellations executor_order_cancellations

Revision ID: bc3d7a040cea
Revises: 1897f4855b07
Create Date: 2026-04-10 20:24:48.433385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3d7a040cea'
down_revision: Union[str, Sequence[str], None] = '1897f4855b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order_cancellations', 'refund_strategy')
    op.drop_column('executor_order_cancellations', 'refund_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('refund_strategy', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('refund_strategy', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
