"""delete column is_closed from table supports_conversations

Revision ID: bf4eb5232097
Revises: 97b25a6eca30
Create Date: 2026-04-14 21:48:52.726430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4eb5232097'
down_revision: Union[str, Sequence[str], None] = '97b25a6eca30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_conversations', 'is_closed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_conversations', sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
