"""change name table information_about_users add columns executor_id customer_id

Revision ID: c4f5b2132f51
Revises: 9f6a310da8b5
Create Date: 2026-05-02 23:46:19.002907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f5b2132f51'
down_revision: Union[str, Sequence[str], None] = '9f6a310da8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_about_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('notification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information_about_users')
    # ### end Alembic commands ###
