"""delete column complainant_id complainant_type from complaints_conversations

Revision ID: cbfba6851e58
Revises: 8dc9e58433f6
Create Date: 2026-04-02 16:25:20.707082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfba6851e58'
down_revision: Union[str, Sequence[str], None] = '8dc9e58433f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('complaints_conversations_complainant_id_fkey', 'complaints_conversations', type_='foreignkey')
    op.drop_column('complaints_conversations', 'complainant_id')
    op.drop_column('complaints_conversations', 'complainant_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints_conversations', sa.Column('complainant_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('complaints_conversations', sa.Column('complainant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('complaints_conversations_complainant_id_fkey', 'complaints_conversations', 'users', ['complainant_id'], ['id'])
    # ### end Alembic commands ###
