"""delete column decision_admin from executor_order_cancellations customer_order_cancellations

Revision ID: d0d85a706739
Revises: bc3d7a040cea
Create Date: 2026-04-10 20:27:06.801959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d85a706739'
down_revision: Union[str, Sequence[str], None] = 'bc3d7a040cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order_cancellations', 'decision_admin')
    op.drop_column('executor_order_cancellations', 'decision_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_order_cancellations', sa.Column('decision_admin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customer_order_cancellations', sa.Column('decision_admin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
