"""create tables payments execcutor_bank_accounts

Revision ID: e34cc5b97f1b
Revises: 087b242a2edb
Create Date: 2026-03-19 21:03:16.482715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e34cc5b97f1b'
down_revision: Union[str, Sequence[str], None] = '087b242a2edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destroy_executed_service')
    op.drop_table('destroy_executed_orders')
    op.drop_table('order_cancellations')
    op.drop_constraint('executors_orders_executor_id_fkey', 'executors_orders', type_='foreignkey')
    op.drop_constraint('executors_orders_order_id_fkey', 'executors_orders', type_='foreignkey')
    op.create_foreign_key(None, 'executors_orders', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'executors_orders', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('executor_bank_account_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('executor_amount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('payments', sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_executor_bank_account_id'), 'payments', ['executor_bank_account_id'], unique=False)
    op.create_index(op.f('ix_payments_executor_id'), 'payments', ['executor_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_foreign_key(None, 'payments', 'executor_bank_accounts', ['executor_bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_executor_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_executor_bank_account_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('payments', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('payments', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'payout_date')
    op.drop_column('payments', 'executor_amount')
    op.drop_column('payments', 'executor_bank_account_id')
    op.drop_constraint(None, 'executors_orders', type_='foreignkey')
    op.drop_constraint(None, 'executors_orders', type_='foreignkey')
    op.create_foreign_key('executors_orders_order_id_fkey', 'executors_orders', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('executors_orders_executor_id_fkey', 'executors_orders', 'users', ['executor_id'], ['id'])
    op.create_table('order_cancellations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reason_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reason_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='order_cancellations_admin_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name='order_cancellations_customer_id_fkey'),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name='order_cancellations_executor_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_cancellations_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='order_cancellations_pkey')
    )
    op.create_table('destroy_executed_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name='destroy_executed_orders_executor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='destroy_executed_orders_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='destroy_executed_orders_pkey')
    )
    op.create_table('destroy_executed_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='destroy_executed_service_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='destroy_executed_service_pkey')
    )
    # ### end Alembic commands ###
